### ISSUE TITLE
A small enhancement after failing to install SIDER by "devtools"

### ISSUE THREAD

**Issue by ruiying-ocean** [healyke/SIDER#24]
I failed to install SIDER according to the [documentation](https://github.com/healyke/SIDER/README.md) this morning,  by just inputting the following codes
```
devtools::install_github("healyke/SIDER@v1.0.0.0", build_vignettes = TRUE, dependencies = "suggests")
```
These are my sreenshots:
<img width="452" alt="批注 2019-07-04 165028" src="https://user-images.githubusercontent.com/38958822/60653792-54a96900-9e7d-11e9-9ca5-3cd7c4cc009f.png">
<img width="457" alt="批注 2019-07-04 165105" src="https://user-images.githubusercontent.com/38958822/60653794-54a96900-9e7d-11e9-84f1-8cf50aa178a6.png">
The Rstudio report an error code, I don't know what's the problem, but I thought this should not be the package issue.
These are my PC info:
```
System: Win10 1903(x64)
R: 3.6.0
Rstudio: Community version1.2.1335
```
I also tried on my Mac, but still failed, my mac system is majavo(10.14.5).
The error message is same ("下标越界" means out of bounds ):
<img width="453" alt="屏幕快照 2019-07-04 17 39 22" src="https://user-images.githubusercontent.com/38958822/60657237-8fae9b00-9e83-11e9-9831-3fe24b532c21.png">
It might be some thing wrong with array or list, but that's just guess. I finally installed it by compiling the source codes.
So I think maybe the README file should add some intructions about installing by compiling source codes. Here are my experiences:
The SIDER package is dependent on [mulTree package](https://github.com/TGuillerme/mulTree), so we should install it first (I successfully installed it by just one step though).
```
devtools::install_github("TGuillerme/mulTree", ref = "release")
```
then download the [source code file](https://github.com/healyke/SIDER/releases) and [Rtools](https://cran.r-project.org/bin/windows/Rtools/), a building tools on windows.

Compile the SIDER package through two steps:
```
cd \path\to\RSDK\ #for me it is "D:\Program Files\R-3.6.0\bin\x64"
.\Rcmd build \path\to\SIDER_source_file
```
then it works and build a *tar.gz file.
![image](https://user-images.githubusercontent.com/38958822/60655568-8a9c1c80-9e80-11e9-9d0f-67ffd633c2b0.png)
At last just install the *.tar.gz file by installing package from local file.

**Comment by healyke** [comment]
Hi Leslie

Thank you for letting us know about the issues regarding installation. 
I have been meaning to update the package recently so will look at the installation procedures again and I will include a description of installing via compelling the source code.

Cheers
Kevin
